"""You are tracking sales by customer and need to know the total sales generated by each unique customer in your dataset."""

import pandas as pd

data = {
    'TransactionID': range(201, 211),
    'CustomerName': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Bob', 'Eve', 'Frank', 'Alice', 'Eve'],
    'TransactionAmount': [15.50, 120.00, 45.75, 80.00, 210.50, 95.00, 15.00, 180.00, 50.00, 30.00]
}
df_transactions = pd.DataFrame(data)

def calculate_customer_totals(df):
    grouped = df.groupby('CustomerName')
    exp_by_cus = grouped.sum()
    return exp_by_cus
result = calculate_customer_totals(df_transactions.copy())
print(result)